### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by byme8** [telehash/telehash-c#133]
Hi, do you have documentation for your protocol? Something like [this](http://www.bittorrent.org/beps/bep_0015.html).

**Comment by byme8** [comment]
I have found [this](https://github.com/telehash/telehash.org/tree/master/v3)), but last commit was at 26 July 2015. Is it reliable today?

**Comment by stpeter** [comment]
The latest spec is at https://github.com/telehash/telehash.org/blob/master/v3/spec/v3.0.0-stable.pdf

Jeremie and Temas (with a bit of help from me) are slowly working on a much simplified v4 protocol, but given our dev timelines at Filament (where the three of us work), I am not sure we'll have time to finish and document that before the middle of this year.

**Comment by byme8** [comment]
Thank you!
