### ISSUE TITLE
review all packet owner cleanup

### ISSUE THREAD

**Issue by quartzjer** [telehash/telehash-c#26]
Most places packets are being created and passed around are not being free'd yet, needs a full review and consistent owner-free pattern applied.

**Comment by utamaro** [comment]
how about using GC, [like boehm GC](http://www.hboehm.info/gc/)?

**Comment by quartzjer** [comment]
I'd love to find a tool to help do leak detection, but yeah since I'm currently using telehash-c for embedded/arduino then tools like this don't work so well :)

**Comment by utamaro** [comment]
https://github.com/StorjPlatform/telehash-c/tree/with_handmade_gc

https://github.com/StorjPlatform/telehash-c/blob/with_handmade_gc/src/lib/tgc.c

https://travis-ci.org/StorjPlatform/telehash-c

only FYI. I made and embeded a simplified version of trivial mark & sweep GC to telehash-c , where
1. GC root must be added manually before GC. GC root is not seached automatically. In telehash-c case, mesh (and some static stuffs) were added. (i.e. mesh is assumed to have everyhing, including indirectly linked stuffs.)
2. Every blocks under GC must be allocated by tgc_malloc().   #define was added in tgc.h to replace standard malloc() to tgc_malloc().
3. garbage collection must be done manually by tgc_gcollect(). now this is done at the end of mesh_receive()
4. stack ,register , etc except tgc_malloced area are not considered. i.e. tgc_gcollect() must be called wherer no auto variables are used as to hold pointers of tgc_malloc'ed area.
5. all data in blocks are assumed as pointer(conservative GC).  From GC root, if a part of pointer's content is in tgc_malloc()'ed pointer range, this pointer is considered alive. And next this pointer's content is checked.
6. GC is not thread-safe.

I believe no spceial and hardware-specific functions  are not used in tgc.c.
But tgc_gcollect() takes some time to be done. maybe some improvements are needed.

I hope it would some help for you :)

**Comment by jbdatko** [comment]
I recommend adding this project to coverity. Coverity is free (as in beer) for open-source projects and is *very* good at finding leaks. It's hands-down the best static-analysis tool I've use and one really should use a static-analysis tool when writing C these days.

I'm in coverity often enough and I can add it there. I've added a few projects so I'm somewhat familiar with the process. It will also identify many other C coding errors.

**Comment by bachp** [comment]
Agree we should take advantages of the coverity findings.
@jbdatko it would be nice if you could setup the scan.

**Comment by jbdatko** [comment]
Telehash-c was already registered with [coverity](https://scan.coverity.com/projects/1792). Perhaps @quartzjer did this? Anyway, it doesn't look like a build was every submitted so once the project maintainer approves me I can submit a build.

**Comment by jbdatko** [comment]
So indeed @quartzjer is the mysterious admin of this coverity scan project, but it appears that I have to be an "administrator" in the coverity system for telehash-c to submit builds.

Jer, can you make me an admin and I'll upload a build to coverity?

**Comment by jbdatko** [comment]
Ouch... 34 errors on the initial [build](https://scan.coverity.com/projects/1792). 

I'll make a separate GitHub issue that is a coverity work-off.

**Comment by quartzjer** [comment]
all major packet flows are now clean, cs2a (and maybe 3a) could leak yet, but I'm closing this general issue and can open specific ones as more leaks found
