### ISSUE TITLE
Base64URL Encoding should not pad

### ISSUE THREAD

**Issue by jbdatko** [telehash/telehash-c#44]
AFAIK, JWS Signatures [should not pad](https://tools.ietf.org/html/draft-jones-json-web-signature-04#appendix-C) the encoded values for header, claims, and signature.

That link contains implementation recommendations for how to add/subtract the padding. The current implementation appears [to pad](https://github.com/telehash/telehash-c/blob/501bd6fb44edc7f7217d449f4c2988293c4b41f9/src/lib/base64.c#L108-L112).

**Comment by quartzjer** [comment]
it adds the padding to the string to be safe, but returns the un-padded length which all things should use the exact returned length... if they don't let's issue them and fix em :)
