### ISSUE TITLE
License is infected by GPL

### ISSUE THREAD

**Issue by utamaro** [telehash/telehash-c#53]
To meet license below
https://github.com/telehash/telehash-c/blob/master/LICENSE

two files which are under GPL must be replaced  
https://github.com/telehash/telehash-c/blob/master/src/e3x/cs1a/aes128.c
https://github.com/telehash/telehash-c/blob/master/src/e3x/cs1a/sha256.c

**Comment by quartzjer** [comment]
Good catch, I've been meaning to audit some of those older libs, it should only impact cs1a builds but these are easy to replace

**Comment by utamaro** [comment]
only FYI.
I replaced these files with ones from wpa_supplicant, which are under BSD license.

https://github.com/StorjPlatform/telehash-c

 tests seems to be passed.
