### ISSUE TITLE
Apparently corrupted lob

### ISSUE THREAD

**Issue by natevw** [telehash/telehash-c#64]
While debugging https://github.com/telehash/telehash-c/issues/58 I [noticed](https://gist.github.com/natevw/a09f57f28e46e40bc071#gistcomment-1508068) the following log message:

```
src/link.c:258 link_receive_handshake() old/bad at: {"at":1437777722 (1437777722,0,1437777723)
```

This is generated by:

```
LOG("old/bad at: %s (%d,%d,%d)",lob_json(inner),lob_get_int(inner,"at"),e3x_exchange_in(link->x,0),e3x_exchange_out(link->x,0));
```

Why is the `lob_json` call returning the string `{"at":1437777722` [sic] — i.e., with an unclosed brace? Looks like the result of `lob_json` is a verbatim copy of the lob's head, so it seems that something is corrupting the lob itself?

**Comment by quartzjer** [comment]
@natevw can you re-verify this after my recent fixes?

**Comment by natevw** [comment]
The lobs are now logged in full:

> src/link.c:263 link_receive_handshake() old handshake: {"at":1441638730,"id":"0245fec6b36c43232199429194c48f71","type":"link","csid":"1a","hashname":"czjax52hopfaw7hbybf3felvstokka6qap3su6qu6hpkkr26g2gq"} (1441638730,0,1441638731)

Was this just a memory management issue related to #68 or what?

**Comment by quartzjer** [comment]
It probably was, def need to get some memory guard/detection tools in place, it's past time to audit and clean up mem usage :)
