### ISSUE TITLE
test_ext_peer sometimes segfaults

### ISSUE THREAD

**Issue by natevw** [telehash/telehash-c#68]
I think this distinct from #58. Sometimes instead of the unit tests failing as in that issue, the process itself actually segfaults!

You can view the full log at <https://gist.github.com/natevw/26913782be7b00299c55> but here's the most interesting bit:

```
test_ext_peer(94169,0x7fff74824300) malloc: *** mach_vm_map(size=12270707960932937728) failed (error code=3)
*** error: can't allocate region
*** set a breakpoint in malloc_error_break to debug
/bin/sh: line 1: 94169 Segmentation fault: 11  ./bin/test_$test
```

…seems that was a lucky capture, as usually it's a pretty silent segfault but this time there was some debug information. That seems like a pretty extreme size to be mapping (allocating?) so I wonder if this is related more to #64.

Actually running under a debugger to get a stacktrace should narrow down the cause even more, but I'm leaving this here for later to continue with the other problem I'm trying to track down.

**Comment by natevw** [comment]
Note that in some informal testing (not really focused on tracking down the segfault itself) this seems to happen about 10% of the time the test is run: https://github.com/telehash/telehash-c/issues/58#issuecomment-128482262 So it might need a bit of persistence to reproduce, but it's not a total unicorn either.

**Comment by dvanduzer** [comment]
I've been reproducing it with a simple shell loop:

> export LOOPCOUNT=0
> while [ $? = 0 ]; do ((LOOPCOUNT++)); echo $LOOPCOUNT; ./test/bin/test_ext_peer; done

The first time I got a segfault after the 35th loop. On a subsequent test it didn't segfault until the 92nd loop. In all segfault cases, it seems to happen right after the final link has reported itself up, which should allow the final test to pass:

`src/link.c:277 link_receive_handshake() link ready`

**Comment by quartzjer** [comment]
I'm def still seeing this even w/ #58 fixed...

**Comment by quartzjer** [comment]
once I caught this w/ lldb it was obvious, probably any memory testing lib would have caught it too, I need to figure out how to get one of those integrated w/ the test suite :)
